# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1023, 589)
        Frame.setAutoFillBackground(False)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(190, 20, 221, 61))
        font = QtGui.QFont()
        font.setFamily("文悦新青年体 (非商业使用) W8")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.TimerLabel = QtWidgets.QLabel(Frame)
        self.TimerLabel.setGeometry(QtCore.QRect(260, 60, 521, 101))
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NP-B")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.TimerLabel.setFont(font)
        self.TimerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimerLabel.setObjectName("TimerLabel")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(921, 0, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.splitter_show = QtWidgets.QSplitter(Frame)
        self.splitter_show.setGeometry(QtCore.QRect(60, 211, 909, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_show.sizePolicy().hasHeightForWidth())
        self.splitter_show.setSizePolicy(sizePolicy)
        self.splitter_show.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_show.setHandleWidth(9)
        self.splitter_show.setObjectName("splitter_show")
        self.label_5 = QtWidgets.QLabel(self.splitter_show)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setText("")
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.splitter_show)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setText("")
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.splitter_show)
        self.label_7.setEnabled(True)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_7.setText("")
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.splitter_show)
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_8.setText("")
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.splitter_show)
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_9.setLineWidth(1)
        self.label_9.setMidLineWidth(0)
        self.label_9.setText("")
        self.label_9.setScaledContents(True)
        self.label_9.setIndent(-1)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.splitter_show)
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_10.setText("")
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.splitter_desk = QtWidgets.QSplitter(Frame)
        self.splitter_desk.setGeometry(QtCore.QRect(60, 150, 909, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_desk.sizePolicy().hasHeightForWidth())
        self.splitter_desk.setSizePolicy(sizePolicy)
        self.splitter_desk.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_desk.setObjectName("splitter_desk")
        self.P1 = QtWidgets.QLabel(self.splitter_desk)
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NK-B")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.P1.setFont(font)
        self.P1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.P1.setObjectName("P1")
        self.P2 = QtWidgets.QLabel(self.splitter_desk)
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NK-B")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.P2.setFont(font)
        self.P2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.P2.setObjectName("P2")
        self.P3 = QtWidgets.QLabel(self.splitter_desk)
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NK-B")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.P3.setFont(font)
        self.P3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.P3.setObjectName("P3")
        self.P4 = QtWidgets.QLabel(self.splitter_desk)
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NK-B")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.P4.setFont(font)
        self.P4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.P4.setObjectName("P4")
        self.P5 = QtWidgets.QLabel(self.splitter_desk)
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NK-B")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.P5.setFont(font)
        self.P5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.P5.setObjectName("P5")
        self.P6 = QtWidgets.QLabel(self.splitter_desk)
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NK-B")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.P6.setFont(font)
        self.P6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.P6.setObjectName("P6")
        self.label_arr = QtWidgets.QLabel(Frame)
        self.label_arr.setGeometry(QtCore.QRect(113, 140, 41, 81))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_arr.setFont(font)
        self.label_arr.setObjectName("label_arr")
        self.label_phase = QtWidgets.QLabel(Frame)
        self.label_phase.setGeometry(QtCore.QRect(60, 20, 121, 61))
        font = QtGui.QFont()
        font.setFamily("文悦新青年体 (非商业使用) W8")
        font.setPointSize(16)
        self.label_phase.setFont(font)
        self.label_phase.setObjectName("label_phase")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(450, 410, 131, 60))
        font = QtGui.QFont()
        font.setFamily("文悦新青年体 (非商业使用) W8")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(466, 20, 121, 61))
        font = QtGui.QFont()
        font.setFamily("文悦新青年体 (非商业使用) W8")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.P1_2 = QtWidgets.QLabel(Frame)
        self.P1_2.setGeometry(QtCore.QRect(60, 470, 144, 48))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1_2.sizePolicy().hasHeightForWidth())
        self.P1_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NK-B")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.P1_2.setFont(font)
        self.P1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.P1_2.setObjectName("P1_2")
        self.P4_2 = QtWidgets.QLabel(Frame)
        self.P4_2.setGeometry(QtCore.QRect(520, 470, 144, 48))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P4_2.sizePolicy().hasHeightForWidth())
        self.P4_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NK-B")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.P4_2.setFont(font)
        self.P4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.P4_2.setObjectName("P4_2")
        self.P5_2 = QtWidgets.QLabel(Frame)
        self.P5_2.setGeometry(QtCore.QRect(672, 470, 144, 48))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P5_2.sizePolicy().hasHeightForWidth())
        self.P5_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NK-B")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.P5_2.setFont(font)
        self.P5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.P5_2.setObjectName("P5_2")
        self.P3_2 = QtWidgets.QLabel(Frame)
        self.P3_2.setGeometry(QtCore.QRect(366, 470, 144, 48))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P3_2.sizePolicy().hasHeightForWidth())
        self.P3_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NK-B")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.P3_2.setFont(font)
        self.P3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.P3_2.setObjectName("P3_2")
        self.P6_2 = QtWidgets.QLabel(Frame)
        self.P6_2.setGeometry(QtCore.QRect(825, 470, 144, 48))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P6_2.sizePolicy().hasHeightForWidth())
        self.P6_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NK-B")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.P6_2.setFont(font)
        self.P6_2.setAlignment(QtCore.Qt.AlignCenter)
        self.P6_2.setObjectName("P6_2")
        self.P2_2 = QtWidgets.QLabel(Frame)
        self.P2_2.setGeometry(QtCore.QRect(213, 470, 144, 48))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P2_2.sizePolicy().hasHeightForWidth())
        self.P2_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NK-B")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.P2_2.setFont(font)
        self.P2_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.P2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.P2_2.setObjectName("P2_2")
        self.label_11 = QtWidgets.QLabel(Frame)
        self.label_11.setGeometry(QtCore.QRect(60, 440, 911, 111))
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setMidLineWidth(0)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_DESK = QtWidgets.QLabel(Frame)
        self.label_DESK.setGeometry(QtCore.QRect(860, 20, 111, 61))
        font = QtGui.QFont()
        font.setFamily("文悦新青年体 (非商业使用) W8")
        font.setPointSize(16)
        self.label_DESK.setFont(font)
        self.label_DESK.setObjectName("label_DESK")
        self.label_VOID = QtWidgets.QLabel(Frame)
        self.label_VOID.setGeometry(QtCore.QRect(860, 70, 111, 51))
        font = QtGui.QFont()
        font.setFamily("文悦新青年体 (非商业使用) W8")
        font.setPointSize(16)
        self.label_VOID.setFont(font)
        self.label_VOID.setObjectName("label_VOID")
        self.label_deskn = QtWidgets.QLabel(Frame)
        self.label_deskn.setGeometry(QtCore.QRect(730, 20, 111, 61))
        font = QtGui.QFont()
        font.setFamily("文悦新青年体 (非商业使用) W8")
        font.setPointSize(16)
        self.label_deskn.setFont(font)
        self.label_deskn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_deskn.setObjectName("label_deskn")
        self.label_voidn = QtWidgets.QLabel(Frame)
        self.label_voidn.setGeometry(QtCore.QRect(730, 70, 111, 51))
        font = QtGui.QFont()
        font.setFamily("文悦新青年体 (非商业使用) W8")
        font.setPointSize(16)
        self.label_voidn.setFont(font)
        self.label_voidn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_voidn.setObjectName("label_voidn")
        self.label_bg = QtWidgets.QLabel(Frame)
        self.label_bg.setGeometry(QtCore.QRect(-10, -10, 1041, 601))
        self.label_bg.setText("")
        self.label_bg.setScaledContents(True)
        self.label_bg.setObjectName("label_bg")
        self.label_bg.raise_()
        self.label_11.raise_()
        self.label.raise_()
        self.TimerLabel.raise_()
        self.pushButton.raise_()
        self.splitter_show.raise_()
        self.splitter_desk.raise_()
        self.label_arr.raise_()
        self.label_phase.raise_()
        self.label_4.raise_()
        self.P1_2.raise_()
        self.P4_2.raise_()
        self.P5_2.raise_()
        self.P3_2.raise_()
        self.P6_2.raise_()
        self.P2_2.raise_()
        self.label_3.raise_()
        self.label_DESK.raise_()
        self.label_VOID.raise_()
        self.label_deskn.raise_()
        self.label_voidn.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Halli Galli！德国心脏病 EVA 10th Edition"))
        self.TimerLabel.setText(_translate("Frame", "00:00"))
        self.pushButton.setText(_translate("Frame", "Result"))
        self.P1.setText(_translate("Frame", "x0"))
        self.P2.setText(_translate("Frame", "x0"))
        self.P3.setText(_translate("Frame", "x0"))
        self.P4.setText(_translate("Frame", "x0"))
        self.P5.setText(_translate("Frame", "x0"))
        self.P6.setText(_translate("Frame", "x0"))
        self.label_arr.setText(_translate("Frame", "$"))
        self.label_phase.setText(_translate("Frame", "发牌阶段"))
        self.label_3.setText(_translate("Frame", "手牌数"))
        self.label_4.setText(_translate("Frame", "准备开始"))
        self.P1_2.setText(_translate("Frame", "0"))
        self.P4_2.setText(_translate("Frame", "0"))
        self.P5_2.setText(_translate("Frame", "0"))
        self.P3_2.setText(_translate("Frame", "0"))
        self.P6_2.setText(_translate("Frame", "0"))
        self.P2_2.setText(_translate("Frame", "0"))
        self.label_DESK.setText(_translate("Frame", "桌上牌数"))
        self.label_VOID.setText(_translate("Frame", "场外牌数"))
        self.label_deskn.setText(_translate("Frame", "0"))
        self.label_voidn.setText(_translate("Frame", "0"))

